### ISSUE TITLE
Calling the entrypoint

### ISSUE THREAD

**Issue by ghost** [CylanceVulnResearch/ReflectiveDLLRefresher#4]
I'd like to modify the project a littlebit to call the EP after a successful load, but for some reason it instantly crashes. Can you see any reason why would it?

The EP call happens right before the cleanup part & the code is (which is quite obvious):

> if (pNtHeader->OptionalHeader.AddressOfEntryPoint)
> {
>     typedef BOOL(WINAPI *PDLL_MAIN)(HMODULE, DWORD, PVOID);
>     PDLL_MAIN EntryPoint = (PDLL_MAIN)((LPBYTE)pLibraryAddr + pNtHeader->OptionalHeader.AddressOfEntryPoint);
>     BOOL ep = EntryPoint((HMODULE)pLibraryAddr, DLL_PROCESS_ATTACH, NULL); // Call the entry point
> }

The problem seems to be some fucked up pointer, because I get a memory access error, but since things are relocated by ReflectiveDLLRefresher, I'm out of ideas what could go wrong.

**Comment by mrjefftang** [comment]
I don't think you can arbitrarily call the entry point of a DLL with DLL_PROCESS_ATTACH again.  There may have been resources allocated or state manipulations that will get undone.

You could with DLL_THREAD_ATTACH since new threads could spawn and the loader will notify each DLL of the new thread.
